### ISSUE TITLE
"parser.parseURL is not a function" error occurs when triggered

### ISSUE THREAD

**Issue by tscholze** [alirawashdeh/rss-reader-alexa#5]
Hi,
I'm using your great repository as an "entry" point into a Alexa skill development project type of thing.

But I always get a. `parser.parseURL is not a function` error in Cloud Watch if I try your code with the Alexa Skill Test Page in the Amazon developer center.

I'm using NodeJS 6.10 and the lambda is deployed to the Ireland region and used from Germany.

Does you or anybody else has an idea why this error occurs?

Thanks!

**Comment by tscholze** [comment]
**Solution**
The repository's code is a little bit outdated. The current version of `rss-parser` has a slidely different call syntax. For more information see: [rss-parser npm.js page](https://www.npmjs.com/package/rss-parser)

**Comment by anshulsinha1101** [comment]
@tscholze could you please help me how to implement rss-parser in Angular 4+ projects

**Comment by anshulsinha1101** [comment]
>'const CORS_PROXY = "https://cors-anywhere.herokuapp.com/"
    let RSSParser =  require('rss-parser/dist/rss-parser.min.js')
    let parser = new RSSParser();
    parser.parseURL(CORS_PROXY + 'https://www.reddit.com/.rss', function (err, feed) {
      console.log(feed);

})`

I am using the following code and i am getting Error TypeError: RSSParser is not a constructor

**Comment by tscholze** [comment]
I'm afraid. I cannot. I have the same code, just instead of `let` I used `var`. I'm not a JavaScript-guy. sorry.

**Comment by robbmueller** [comment]
@tscholze did you fix the rss-parser call? I am currently stuck at the same error.

**Comment by tscholze** [comment]
@robbmueller I used another version. Please see my comment above: https://github.com/alirawashdeh/rss-reader-alexa/issues/5#issuecomment-362913311

**Comment by tscholze** [comment]
@anshulsinha1101 sorry for not answering you. I have no deep knowledge in JS. I hope you got it working!

**Comment by robbmueller** [comment]
For the record. It worked with rss-parser@2.12.1
